Function funcaoExterna1(pars1: Boolean) : String;
Var
  simOuNao : Boolean;
  num1: Integer;
  num2: Real;
  frase: String;

Begin
  Procedure funcaoInterna1Externa2(qualquerCoisa: String);
  Begin
  End;

  Procedure twice(podeTwuceNoGrupo: Boolean);
  Var
    nomes: String;
  Begin
  End;

  Function calcularNome(nome : String) : Integer;
  Var
    aux: Integer;
    tam: Integer;
  Begin
    Function funcaoFinal(theLast : Boolean): Boolean;
    Begin
    End;
  End;
End;

  
